# Trigger on pull request to master (+ allow manual runs of this workflow)
# Checkout repo, install Node.js, run test

name: pr-workflow

on:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/npm-install@v2
        run: npm i
      - name: Run tests
        uses: actions/npm-install@v2
        run: npm test
